# Generated by Django 4.2.16 on 2024-11-27 07:30

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickname', models.CharField(max_length=50, unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('남', '남'), ('여', '여')], max_length=2)),
                ('assets', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('job', models.CharField(choices=[('경영·사무', '경영·사무'), ('금융·보험', '금융·보험'), ('교육', '교육'), ('자연·사회과학', '자연·사회과학'), ('법률·경찰·소방·교도·국방', '법률·경찰·소방·교도·국방'), ('보건·의료', '보건·의료'), ('사회복지·종교', '사회복지·종교'), ('문화·예술·디자인·방송', '문화·예술·디자인·방송'), ('운전·운송', '운전·운송'), ('영업·판매', '영업·판매'), ('경비·청소', '경비·청소'), ('미용·숙박·여행·오락·스포츠', '미용·숙박·여행·오락·스포츠'), ('음식서비스', '음식서비스'), ('건설', '건설'), ('기계', '기계'), ('재료', '재료'), ('화학', '화학'), ('섬유·의복', '섬유·의복'), ('전기·전자', '전기·전자'), ('정보통신', '정보통신'), ('식품가공', '식품가공'), ('인쇄·목재·가구·공예', '인쇄·목재·가구·공예'), ('환경·에너지·안전', '환경·에너지·안전'), ('농림어업', '농림어업'), ('학생', '학생'), ('무직', '무직')], max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
